spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/leaf
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    platform: mysql
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
thymeleaf:
   mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:mapper/*.xml
